import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Mart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
